---
- hosts: centos
  user: ansible
  become: yes
  vars:
    motd: "Testing the method using Handlers \n"
  tasks: 
  -  name: configure a MOTD(message of the day)
     copy:
       content: "{{ motd }}"
       dest: /etc/motd
     notify: MOTD changed
  handlers:
  - name: MOTD changed
    debug:
      msg: The MOTD was changes
