---
- hosts: all 
  user: ansible
  become: yes
  vars:
    motd_centos: "Testing the method in centos \n"
    motd_ubuntu: "Testing the method in ubuntu \n"
  tasks: 
  -  name: configure a MOTD(message of the day)
     copy:
       content: "{{ motd_centos }}"
       dest: /etc/motd
     notify: MOTD changed
     when: ansible_distribution == "CentOS"
  -  name: configure a MOTD(message of the day)
     copy:
       content: "{{ motd_ubuntu }}"
       dest: /etc/motd
     notify: MOTD changed
     when: ansible_distribution == "Ubuntu"
  handlers:
  - name: MOTD changed
    debug:
      msg: The MOTD was changes
