---
-
  hosts: centos
  user: ansible
  become: true
  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        content: "Welcome to {{ ansible_distribution }}  Ansible \n"
        dest: /etc/motd
      notify: MOTD changed
 
  # Handlers: handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD was changed 
 
