---
# YAML documents begin with the document separator ---
-
  hosts: centos 
  tasks:
    - name: Ansible Jinja2 if varible is defined ( where variable is defined )
      debug:
        msg: >
             --== Ansible Jinja2 if varible is defined ( where variable is defined ) ==--

             {% set example_variable = 'defined' -%}
             {% if example_variable is defined -%}
                example_variable is defined
             {% else -%}
                example_variable is not defined
             {% endif %}

...
