---
-
  hosts: centos
  tasks:
    - name: Ansible Jinja2 for statement
      debug:
        msg: >
             --== Ansible Jinja2 for statement ==--

             {% for entry in ansible_all_ipv4_addresses -%}
                IP Address entry {{ loop.index }} = {{ entry }}
             {% endfor %}

...
